/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FinalProject;

import java.util.ArrayList;

/**
 *
 * @author finkelmanj7070
 */
public class UI extends javax.swing.JFrame {

    String secName = "";
     String secTck = "";
     Double cp;
     Double er;
     String fl = "";
     Boolean sbtn;
     Boolean mfbtn;
     Boolean etfbtn;
     public  ArrayList<Security> secList = new ArrayList<>();
    
    /**
     * Creates new form UI
     */
    public UI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        secTxtField = new javax.swing.JTextField();
        tckTextField = new javax.swing.JTextField();
        cpTextField = new javax.swing.JTextField();
        flTextField = new javax.swing.JTextField();
        erTextField = new javax.swing.JTextField();
        secBtn = new javax.swing.JButton();
        tckBtn = new javax.swing.JButton();
        cpBtn = new javax.swing.JButton();
        flBtn = new javax.swing.JButton();
        erBtn = new javax.swing.JButton();
        stockBtn = new javax.swing.JButton();
        etfBtn = new javax.swing.JButton();
        mfBtn = new javax.swing.JButton();
        newSec = new javax.swing.JButton();
        viewSecListBtn = new javax.swing.JButton();
        viewSecListTxtField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Financial Modeling");

        jLabel2.setText("by John Finkelman");
        jLabel2.setToolTipText("");

        jLabel3.setText("Security Name:");

        jLabel4.setText("Security Ticker:");

        jLabel5.setText("Security Current Price:");

        jLabel6.setText("Security File Location:");

        jLabel7.setText("Security Expense Ratio (if applicable):");

        cpTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpTextFieldActionPerformed(evt);
            }
        });

        secBtn.setText("Submit");
        secBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secBtnActionPerformed(evt);
            }
        });

        tckBtn.setText("Submit");
        tckBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tckBtnActionPerformed(evt);
            }
        });

        cpBtn.setText("Submit");
        cpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpBtnActionPerformed(evt);
            }
        });

        flBtn.setText("Submit");
        flBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flBtnActionPerformed(evt);
            }
        });

        erBtn.setText("Add Security and Submit");
        erBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                erBtnActionPerformed(evt);
            }
        });

        stockBtn.setText("Stock");
        stockBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockBtnActionPerformed(evt);
            }
        });

        etfBtn.setText("ETF");
        etfBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etfBtnActionPerformed(evt);
            }
        });

        mfBtn.setText("Mutual Fund");
        mfBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mfBtnActionPerformed(evt);
            }
        });

        newSec.setText("Add Another Security");
        newSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSecActionPerformed(evt);
            }
        });

        viewSecListBtn.setText("View Added Securities");
        viewSecListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSecListBtnActionPerformed(evt);
            }
        });

        jLabel8.setText("Security to Access:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(cpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cpBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(flTextField))
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(erTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(erBtn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(flBtn))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(17, 17, 17)
                                    .addComponent(tckTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tckBtn))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(secTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(42, 42, 42)
                                    .addComponent(secBtn)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(207, 207, 207)
                                .addComponent(mfBtn))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(stockBtn)
                        .addGap(59, 59, 59)
                        .addComponent(etfBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(newSec))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(viewSecListBtn)
                        .addGap(18, 18, 18)
                        .addComponent(viewSecListTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stockBtn)
                    .addComponent(etfBtn)
                    .addComponent(mfBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(secTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tckTextField)
                        .addComponent(tckBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpBtn))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6)
                    .addComponent(flTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(erTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(erBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(newSec)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewSecListBtn)
                    .addComponent(viewSecListTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(92, 92, 92))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void erBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_erBtnActionPerformed
        // TODO add your handling code here:
        
        er = Double.parseDouble(erTextField.getText());
        erTextField.setEditable(false);
        
        if (sbtn) {
            Stocks stk = new Stocks(secName, secTck, cp, fl );
            secList.add(stk);
        }
        
        if (etfbtn) {
            ETFs etf = new ETFs(secName, secTck, cp, fl, er );
            secList.add(etf);
        }
        
        if (mfbtn) {
            MutualFunds mtf = new MutualFunds(secName, secTck, cp, fl, er );
            secList.add(mtf);
        }
        
        
        
        
        
    }//GEN-LAST:event_erBtnActionPerformed

    private void secBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secBtnActionPerformed
        // TODO add your handling code here:
        
        secName = secTxtField.getText();
        secTxtField.setEditable(false);
    }//GEN-LAST:event_secBtnActionPerformed

    private void cpTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpTextFieldActionPerformed
        // TODO add your handling code here:
        
        // er = Double.parseDouble(cpTextField.getText());
    }//GEN-LAST:event_cpTextFieldActionPerformed

    private void flBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flBtnActionPerformed
        // TODO add your handling code here:
        
        fl = flTextField.getText();
        flTextField.setEditable(false);
    }//GEN-LAST:event_flBtnActionPerformed

    private void tckBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tckBtnActionPerformed
        // TODO add your handling code here:
        
        secTck = tckTextField.getText();
        tckTextField.setEditable(false);
    }//GEN-LAST:event_tckBtnActionPerformed

    private void etfBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etfBtnActionPerformed
        // TODO add your handling code here:
        
     sbtn = false;
     mfbtn = false;
     etfbtn = true;
     stockBtn.setVisible(false);
     mfBtn.setVisible(false);
     
    }//GEN-LAST:event_etfBtnActionPerformed

    private void stockBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockBtnActionPerformed
        // TODO add your handling code here:
      sbtn = true;
     mfbtn = false;
     etfbtn = false;
     etfBtn.setVisible(false);
     mfBtn.setVisible(false);
        
    }//GEN-LAST:event_stockBtnActionPerformed

    private void mfBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mfBtnActionPerformed
        // TODO add your handling code here:
        
     sbtn = false;
     mfbtn = true;
     etfbtn = false;
     etfBtn.setVisible(false);
     stockBtn.setVisible(false);
    }//GEN-LAST:event_mfBtnActionPerformed

    private void cpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpBtnActionPerformed
        // TODO add your handling code here:
        
        cp = Double.parseDouble(cpTextField.getText());
        cpTextField.setEditable(false);
    }//GEN-LAST:event_cpBtnActionPerformed

    private void newSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSecActionPerformed
        // TODO add your handling code here:
        etfBtn.setVisible(true);
     mfBtn.setVisible(true);
     stockBtn.setVisible(true);
     tckTextField.setEditable(true);
     secTxtField.setEditable(true);
     cpTextField.setEditable(true);
     flTextField.setEditable(true);
      erTextField.setEditable(true);
        
    }//GEN-LAST:event_newSecActionPerformed

    private void viewSecListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSecListBtnActionPerformed
        // TODO add your handling code here:
        viewSecListTxtField.setText(secList.toString());
    }//GEN-LAST:event_viewSecListBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cpBtn;
    private javax.swing.JTextField cpTextField;
    private javax.swing.JButton erBtn;
    private javax.swing.JTextField erTextField;
    private javax.swing.JButton etfBtn;
    private javax.swing.JButton flBtn;
    private javax.swing.JTextField flTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton mfBtn;
    private javax.swing.JButton newSec;
    private javax.swing.JButton secBtn;
    private javax.swing.JTextField secTxtField;
    private javax.swing.JButton stockBtn;
    private javax.swing.JButton tckBtn;
    private javax.swing.JTextField tckTextField;
    private javax.swing.JButton viewSecListBtn;
    private javax.swing.JTextField viewSecListTxtField;
    // End of variables declaration//GEN-END:variables
}
